splitter:
  root: GMDN_SPLITS/
  class_name: data.splitter.SIRSplitter
  args:
    n_outer_folds: 1
    n_inner_folds: 1
    seed: 42
dataset:
  root: DATA/ERDOS_RENYI
  class_name: data.dataset.ErdosRenyiDataset
  args:
    root: DATA/ERDOS_RENYI
    name: erdos_renyi
    size: 100
    connectivity: 0.01@0.05@0.1@0.2
